version: '3'
services:
 database:
  container_name: r1ds_discount_db
  image: mysql:8.0
  volumes:
   - database:/var/lib/mysql
  ports:
   - "3334:3306"
  environment:
   - MYSQL_USER=discount
   - MYSQL_PASSWORD=ASecurePasswd
   - MYSQL_RANDOM_ROOT_PASSWORD=yes
   - MYSQL_DATABASE=discount_service

 backend:
  container_name: r1ds_discount_backend
  build: .
  ports:
   - "4575:3000"
  environment:
   - MYSQL_CONN=discount:ASecurePasswd@tcp(r1ds_discount_db:3306)/discount_service?charset=utf8&parseTime=true
   - WALLET_ENDPOINT=http://r1ds_wallet_backend:3000
  depends_on:
   - database

volumes:
 database:
